---
- name: Install remote user
  hosts: all
  vars_files:
    - vars/ansible-playbook-vars.yaml
  roles:
    - sudoers

- name: Install and configure Utility Nodes
  hosts: module_utility_node_servers
  vars_files:
    - vars/ansible-playbook-vars.yaml
  roles:
    - dns
    - ntp
