name: Destroy Terraform project
on:
    workflow_dispatch:
jobs:
    destroy:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            terraform_workspace:
            - cluster_1
            - cluster_2
        env:
          TF_WORKSPACE: "${{ matrix.terraform_workspace }}"
        steps:
        - name: Checkout VCS
          uses: actions/checkout@v3

        - name: Install and configure Terraform
          uses: hashicorp/setup-terraform@v2
          with:
              terraform_version: 1.5.7
              cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Terraform Init
          run: terraform init

        - name: Terraform Destroy
          run: terraform destroy -auto-approve
