---
name: Destroy Terraform project
on:
  workflow_dispatch:

env:
  TERRAFORM_DIRECTORY: "./terraform"

jobs:
  destroy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_workspace:
          - cluster_1
          - cluster_2
    env:
      TF_WORKSPACE: "${{ matrix.terraform_workspace }}"
    steps:
      - name: Checkout VCS
        uses: actions/checkout@v3

      - name: Install and configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform -chdir=${{ env.TERRAFORM_DIRECTORY }} init

      - name: Terraform Destroy
        run: terraform -chdir=${{ env.TERRAFORM_DIRECTORY }} destroy -auto-approve
