name: Apply Terraform project
on:
    workflow_dispatch:
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout VCS
          uses: actions/checkout@v3

        - name: Install and configure Terraform
          uses: hashicorp/setup-terraform@v2
          with:
              terraform_version: 1.5.7
              cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Terraform Init
          run: terraform init

        - name: Terraform Validate
          run: terraform validate
    apply:
        runs-on: ubuntu-latest
        needs: [validate]
        steps:
        - name: Checkout VCS
          uses: actions/checkout@v3

        - name: Install and configure Terraform
          uses: hashicorp/setup-terraform@v2
          with:
              terraform_version: 1.5.7
              cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Terraform Init
          run: terraform init

        - name: Terraform Apply
          run: terraform apply -auto-approve