name: Destroy Terraform project
on:
    workflow_dispatch:
jobs:
    destoy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout VCS
          uses: actions/checkout@v3

        - name: Install and configure Terraform
          uses: hashicorp/setup-terraform@v2
          with:
              terraform_version: 1.5.7
              cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Terraform Init
          run: terraform init

        - name: Terraform Destroy
          run: terraform destroy -auto-approve